version: '3.5'
services:
  webapp:
    build: .
    ports:
      - 9000:9000
    environment:
      - MONGO_HOST=mongodb://mongodb:27017
      - DB_NAME=people
    networks:
      - simple_crud
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - simple_crud

networks:
  simple_crud: